### ISSUE TITLE
MacOS 下存在内存泄露 使用时间长后会报错退出

### ISSUE THREAD

**Issue by goldyard** [tangshimin/typing-learner#90]
<img width="996" alt="image" src="https://user-images.githubusercontent.com/2938387/188392790-a66ab23c-d68f-4747-90be-01136683dc42.png">
Macbook M1 16G内存， 使用大约半小时后会报错退出。

**Comment by tangshimin** [comment]
这个 bug 经常出现吗？

**Comment by tangshimin** [comment]
你用命令行的方式启动
在 Typing Learner 的图标上，按鼠标右键 > 选择显示包内容 > 进入 Contents > 进入 MacOS > 然后双击 `Typing Learner`
如果又出现了这个问题，就把命令行里的详细信息发过来。

**Comment by goldyard** [comment]
出现频率挺高的， 我今天一天遭遇4～5次了。
<img width="820" alt="image" src="https://user-images.githubusercontent.com/2938387/188475387-a577d913-6b6f-4711-a3e6-b0685a6475ea.png">

**Comment by goldyard** [comment]
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/2938387/188475509-b6d827ea-1837-4aed-b102-3d18162cc154.png">
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/2938387/188475553-1e991cf1-2b0c-468c-bbfb-f81ec19faa47.png">
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/2938387/188475617-88c325e5-39fa-403f-91f9-8ef7c2998d69.png">
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/2938387/188475706-f6c352ac-4d3a-4833-910b-fa559caf1ad7.png">
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/2938387/188475761-ff85ef8b-d256-4913-b149-febdbbb12323.png">

**Comment by goldyard** [comment]
/Applications/Typing\ Learner.app/Contents/MacOS/Typing\ Learner ; exit;
2022-09-05 22:23:14.542 Typing Learner[61686:1324399] Bad JNI lookup accessibilityHitTest
2022-09-05 22:23:14.543 Typing Learner[61686:1324399] (
	0   libawt_lwawt.dylib                  0x0000000128550add -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x000000012850b6b0 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff814c4f7be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff8147e2bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff8147b259c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff8174705da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff817491ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff81744f729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff811a43b11 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff811a439f3 __CFRunLoopDoSource1 + 615
	10  CoreFoundation                      0x00007ff811a42067 __CFRunLoopRun + 2419
	11  CoreFoundation                      0x00007ff811a41034 CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff81ab5d5e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff81ab5d213 ReceiveNextEventCommon + 283
	14  HIToolbox                           0x00007ff81ab5d0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff8143b1fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff8143b066a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010d90556a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff8143a2d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010d905339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libawt_lwawt.dylib                  0x0000000128570c90 +[AWTStarter starter:headless:] + 496
	21  libosxapp.dylib                     0x000000010d90700f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff8127f74f7 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff811a4337a __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff811a432e2 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff811a43060 __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff811a41a70 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff811a41034 CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010ccaf0b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010ccaac15 JLI_Launch + 1413
	30  Typing Learner                      0x00000001045a0f2e jvmLauncherStartJvm + 142
	31  Typing Learner                      0x000000010459f8cd _ZN3Jvm6launchEv + 893
	32  Typing Learner                      0x00000001045a2558 _ZN12_GLOBAL__N_115initJvmLauncherEv + 904
	33  Typing Learner                      0x00000001045a4f69 _ZN3app6launchERKSt9nothrow_tPFvvEP11LogAppender + 233
	34  dyld                                0x000000020493d52e start + 462
	35  ???                                 0x0000000000000003 0x0 + 3
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
2022-09-05 22:23:15.722 Typing Learner[61686:1324399] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
2022-09-05 22:23:21.991 Typing Learner[61686:1324399] Bad JNI lookup accessibilityHitTest
2022-09-05 22:23:21.994 Typing Learner[61686:1324399] (
	0   libawt_lwawt.dylib                  0x0000000128550add -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x000000012850b6b0 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff814c4f7be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff8147e2bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff8147b259c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff8174705da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff817491ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff81744f729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff811a43b11 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff811a439f3 __CFRunLoopDoSource1 + 615
	10  CoreFoundation                      0x00007ff811a42067 __CFRunLoopRun + 2419
	11  CoreFoundation                      0x00007ff811a41034 CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff81ab5d5e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff81ab5d213 ReceiveNextEventCommon + 283
	14  HIToolbox                           0x00007ff81ab5d0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff8143b1fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff8143b066a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010d90556a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff8143a2d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010d905339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libawt_lwawt.dylib                  0x0000000128570c90 +[AWTStarter starter:headless:] + 496
	21  libosxapp.dylib                     0x000000010d90700f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff8127f74f7 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff811a4337a __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff811a432e2 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff811a43060 __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff811a41a70 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff811a41034 CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010ccaf0b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010ccaac15 JLI_Launch + 1413
	30  Typing Learner                      0x00000001045a0f2e jvmLauncherStartJvm + 142
	31  Typing Learner                      0x000000010459f8cd _ZN3Jvm6launchEv + 893
	32  Typing Learner                      0x00000001045a2558 _ZN12_GLOBAL__N_115initJvmLauncherEv + 904
	33  Typing Learner                      0x00000001045a4f69 _ZN3app6launchERKSt9nothrow_tPFvvEP11LogAppender + 233
	34  dyld                                0x000000020493d52e start + 462
	35  ???                                 0x0000000000000003 0x0 + 3
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
2022-09-05 22:24:24.045 Typing Learner[61686:1324399] Bad JNI lookup accessibilityHitTest
2022-09-05 22:24:24.047 Typing Learner[61686:1324399] (
	0   libawt_lwawt.dylib                  0x0000000128550add -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x000000012850b6b0 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff814c4f7be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff8147e2bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff8147b259c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff8174705da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff817491ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff81744f729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff811a43b11 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff811a439f3 __CFRunLoopDoSource1 + 615
	10  CoreFoundation                      0x00007ff811a42067 __CFRunLoopRun + 2419
	11  CoreFoundation                      0x00007ff811a41034 CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff81ab5d5e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff81ab5d34a ReceiveNextEventCommon + 594
	14  HIToolbox                           0x00007ff81ab5d0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff8143b1fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff8143b066a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010d90556a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff8143a2d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010d905339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libawt_lwawt.dylib                  0x0000000128570c90 +[AWTStarter starter:headless:] + 496
	21  libosxapp.dylib                     0x000000010d90700f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff8127f74f7 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff811a4337a __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff811a432e2 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff811a43060 __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff811a41a70 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff811a41034 CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010ccaf0b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010ccaac15 JLI_Launch + 1413
	30  Typing Learner                      0x00000001045a0f2e jvmLauncherStartJvm + 142
	31  Typing Learner                      0x000000010459f8cd _ZN3Jvm6launchEv + 893
	32  Typing Learner                      0x00000001045a2558 _ZN12_GLOBAL__N_115initJvmLauncherEv + 904
	33  Typing Learner                      0x00000001045a4f69 _ZN3app6launchERKSt9nothrow_tPFvvEP11LogAppender + 233
	34  dyld                                0x000000020493d52e start + 462
	35  ???                                 0x0000000000000003 0x0 + 3
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
[1600.377s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Unknown Source)
	at java.base/java.util.Timer.<init>(Unknown Source)
	at components.TypingWordKt$TypingWord$1$1$1$2$3$checkWordInput$1.invoke(TypingWord.kt:781)
	at components.TypingWordKt$TypingWord$1$1$1$2$3$checkWordInput$1.invoke(TypingWord.kt:733)
	at components.TypingWordKt$TypingWord$1$1$1$2$3$3$3$1$1.invoke(TypingWord.kt:1123)
	at components.TypingWordKt$TypingWord$1$1$1$2$3$3$3$1$1.invoke(TypingWord.kt:1123)
	at components.WordKt$Word$1$2$1$2$1.invokeSuspend(Word.kt:106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:56)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:51)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:85)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:33)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeLayer$coroutineExceptionHandler$1@5b4a14, androidx.compose.runtime.BroadcastFrameClock@1941f192, StandaloneCoroutine{Cancelling}@450a6b2c, FlushCoroutineDispatcher@12bdc33b]
2022-09-05 22:49:49.671 Typing Learner[61686:1324399] Bad JNI lookup accessibilityHitTest
2022-09-05 22:49:49.675 Typing Learner[61686:1324399] (
	0   libawt_lwawt.dylib                  0x0000000128550add -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x000000012850b6b0 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff814c4f7be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff8147e2bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff8147b259c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff8174705da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff817491ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff81744f729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff811a43b11 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff811a439f3 __CFRunLoopDoSource1 + 615
	10  CoreFoundation                      0x00007ff811a42067 __CFRunLoopRun + 2419
	11  CoreFoundation                      0x00007ff811a41034 CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff81ab5d5e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff81ab5d34a ReceiveNextEventCommon + 594
	14  HIToolbox                           0x00007ff81ab5d0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff8143b1fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff8143b066a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010d90556a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff8143a2d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010d905339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libawt_lwawt.dylib                  0x0000000128570c90 +[AWTStarter starter:headless:] + 496
	21  libosxapp.dylib                     0x000000010d90700f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff8127f74f7 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff811a4337a __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff811a432e2 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff811a43060 __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff811a41a70 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff811a41034 CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010ccaf0b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010ccaac15 JLI_Launch + 1413
	30  Typing Learner                      0x00000001045a0f2e jvmLauncherStartJvm + 142
	31  Typing Learner                      0x000000010459f8cd _ZN3Jvm6launchEv + 893
	32  Typing Learner                      0x00000001045a2558 _ZN12_GLOBAL__N_115initJvmLauncherEv + 904
	33  Typing Learner                      0x00000001045a4f69 _ZN3app6launchERKSt9nothrow_tPFvvEP11LogAppender + 233
	34  dyld                                0x000000020493d52e start + 462
	35  ???                                 0x0000000000000003 0x0 + 3
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
2022-09-05 22:50:05.671 Typing Learner[61686:1324399] Bad JNI lookup accessibilityHitTest
2022-09-05 22:50:05.674 Typing Learner[61686:1324399] (
	0   libawt_lwawt.dylib                  0x0000000128550add -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x000000012850b6b0 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff814c4f7be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff8147e2bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff8147b259c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff8174705da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff817491ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff81744f729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff811a43b11 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff811a439f3 __CFRunLoopDoSource1 + 615
	10  CoreFoundation                      0x00007ff811a42067 __CFRunLoopRun + 2419
	11  CoreFoundation                      0x00007ff811a41034 CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff81ab5d5e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff81ab5d213 ReceiveNextEventCommon + 283
	14  HIToolbox                           0x00007ff81ab5d0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff8143b1fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff8143b066a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010d90556a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff8143a2d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010d905339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libawt_lwawt.dylib                  0x0000000128570c90 +[AWTStarter starter:headless:] + 496
	21  libosxapp.dylib                     0x000000010d90700f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff8127f74f7 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff811a4337a __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff811a432e2 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff811a43060 __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff811a41a70 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff811a41034 CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010ccaf0b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010ccaac15 JLI_Launch + 1413
	30  Typing Learner                      0x00000001045a0f2e jvmLauncherStartJvm + 142
	31  Typing Learner                      0x000000010459f8cd _ZN3Jvm6launchEv + 893
	32  Typing Learner                      0x00000001045a2558 _ZN12_GLOBAL__N_115initJvmLauncherEv + 904
	33  Typing Learner                      0x00000001045a4f69 _ZN3app6launchERKSt9nothrow_tPFvvEP11LogAppender + 233
	34  dyld                                0x000000020493d52e start + 462
	35  ???                                 0x0000000000000003 0x0 + 3
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest

Saving session...completed.
Deleting expired sessions...none found.

[进程已完成]

**Comment by goldyard** [comment]
不过未必是这个问题导致的内存泄露， 这个错误按照当前发生的频率， 感觉不一定是导致内存溢出的原因， 建议用JProb之类的东西dump个内存镜像看下究竟是哪些东西在内存里面变多。 我觉得可能是和大量使用JSON有关， 我没具体看内存镜像。

**Comment by tangshimin** [comment]
要升级 JDK 版本，你加一下[QQ群](https://github.com/tangshimin/typing-learner/issues/75),我升级后把安装包发到群里，你再测试一下，我没有 M1芯片的 macOS。

**Comment by goldyard** [comment]
好啊，我申请了加群， 麻烦通过下 光牙 2655653

tangshimin ***@***.***> 于2022年9月5日周一 23:16写道：
